### ISSUE TITLE
spin_dataloaders = True

### ISSUE THREAD

**Issue by kashifmunir92** [mosaicml/llm-foundry#507] opened 2023-08-08 06:00 UTC
I have a question, if I start training using N nodes (each node with 8 GPUs), and then after saving checkpoints. I can continue training from previous saved ckpt and spin_dataloaders=True. But my question is if I increase nodes to N+1 and start training from previous ckpt. Would the data_loader be spun according to the already seen datapoints? or do I need to manually skip the already seen datapoints?

**Comment by karan6181** [comment] 2023-08-28 14:49
Duplicate of https://github.com/mosaicml/llm-foundry/issues/508. 

@kashifmunir92 Please check my answer in issue #508

**Closed by karan6181** 2023-08-28 14:49 UTC
Labels: question
