### ISSUE TITLE
Add Flash attention 2 support for MPT

### ISSUE THREAD

**Issue by rajveer43** [mosaicml/llm-foundry#638] opened 2023-09-29 11:24 UTC

**Comment by MFajcik** [comment] 2023-10-02 07:59
Flash Attention 2 implementation is not written with explicit attention biasing support (MPT uses alibi). AFAIK only triton flash attention supports that. Same problem happens for AMD (released implementation does not support biasing).

So I guess this will take some time...

**Comment by dakinggg** [comment] 2023-10-05 07:10
Duplicate of #464

**Closed by dakinggg** 2023-10-05 07:10 UTC
Labels: enhancement
