### ISSUE TITLE
TypeError: init() got an unexpected keyword argument 'approximate' when using mosaicml/mpt-7b-instruct model

### ISSUE THREAD

**Issue by souvik0306** [mosaicml/llm-foundry#174] opened 2023-05-19 15:16 UTC
I am trying to use the "mosaicml/mpt-7b-instruct" model for my project. However, when I instantiate the model, I encounter a TypeError with the message "init() got an unexpected keyword argument 'approximate'". This error seems to be related to the nn.GELU activation function.

Here is the relevant code snippet:
```

generate = InstructionTextGenerationPipeline(
    "mosaicml/mpt-7b-instruct",
    torch_dtype=torch.bfloat16,
    trust_remote_code=True,
)
stop_token_ids = generate.tokenizer.convert_tokens_to_ids([""])

```
I am using the latest version of the transformers library and the model checkpoint. I have also ensured that all the dependencies are up to date.

Can anyone help me understand why I am getting this error and how I can resolve it? Is there a specific version of the "mosaicml/mpt-7b-instruct" model that supports the 'approximate' argument in nn.GELU?

Any assistance would be greatly appreciated. Thank you!

Note: Make sure to include relevant details about your environment, such as the versions of transformers and PyTorch you are using.

My System Specs - 
NVIDIA GeForce RTX 4090
PyTorch Cuda 11.1

**Comment by souvik0306** [comment] 2023-05-19 15:17
I am trying to follow a Jupyter Notebook implementation of MPT-7B-Instruct - https://colab.research.google.com/drive/1s2beg55SEV8ICHufhwcflYtUNskTX8kO?usp=sharing#scrollTo=6qHrby3n0109

**Comment by hanlint** [comment] 2023-05-19 15:59
Hello @souvik0306 , the `approximate` argument was introduced to `nn.GELU` in PyTorch 1.12 (https://github.com/pytorch/pytorch/pull/61439). Updating to the latest pytorch should fix your issue.

**Comment by souvik0306** [comment] 2023-05-20 11:26
> 

I upgraded the PyTorch version to 2.0.1, however still while trying to Load the Model on Cuda, the Kernel crashed. 

RAM - 24 GB
NVIDIA GeForce RTX 4090
PyTorch Cuda 11.7

**Comment by hanlint** [comment] 2023-05-20 22:59
Hi @souvik0306 , my mistake. Torch 2.0 is still not well supported. Could you install torch 1.13? That is the recommended torch version.

**Comment by souvik0306** [comment] 2023-05-21 05:28
Hi, @hanlint  I tried it with PyTorch 1.13.0, however, it still crashed. It would be great if you can provide - 
1. A requirements.txt file
2. A Google Colab Notebook to use the pre-trained model

**Comment by souvik0306** [comment] 2023-05-23 14:03
@hanlint Any comments?

**Comment by souvik0306** [comment] 2023-05-23 14:32
Error - 
```
UserWarning: Using `attn_impl: torch`. If your model does not use `alibi` or `prefix_lm` we recommend using `attn_impl: flash` otherwise we recommend using `attn_impl: triton`.
  warnings.warn('Using `attn_impl: torch`. If your model does not use `alibi` or ' + '`prefix_lm` we recommend using `attn_impl: flash` otherwise ' + 'we recommend using `attn_impl: triton`.')
Loading checkpoint shards:   0%|                                                                                                                                 | 0/2 [00:00<?, ?it/s]Killed
```
Code -
```

# Initialize the model and tokenizer
generate = InstructionTextGenerationPipeline(
    "mosaicml/mpt-7b-instruct",
    torch_dtype=torch.bfloat16,
    trust_remote_code=True,
)
stop_token_ids = generate.tokenizer.convert_tokens_to_ids(["<|endoftext|>"])


# Define a custom stopping criteria
class StopOnTokens(StoppingCriteria):
    def __call__(self, input_ids: torch.LongTensor, scores: torch.FloatTensor, **kwargs) -> bool:
        for stop_id in stop_token_ids:
            if input_ids[0][-1] == stop_id:
                return True
        return False

```

**Comment by souvik0306** [comment] 2023-05-24 04:05
@hanlint @vchiley What is the minimum vRAM GPU requirement - 
As I was able to run the code on A100 with a 40GB RAM not on RTX 4090 with 24 GB RAM

**Comment by hanlint** [comment] 2023-05-25 03:07
Hello -- closing this as duplicate of #196 -- let's answer the questions there!

**Closed by hanlint** 2023-05-25 03:07 UTC
